/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        tertiary: '#1d2022',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#323537',
        'inverse-primary': '#b0c6ff',
        primary: '#001d4e',
        'on-secondary-fixed': '#0d1c2e',
        'on-tertiary-fixed-variant': '#444749',
        outline: '#747782',
        'on-secondary-container': '#556379',
        'secondary-container': '#d2e1fa',
        'surface-container-low': '#f4f3fa',
        'inverse-surface': '#2f3035',
        'surface-dim': '#dad9e0',
        'on-error-container': '#93000a',
        'on-background': '#1a1b20',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f1f0f7',
        'surface-container': '#eeedf4',
        'surface-container-highest': '#e2e2e8',
        'tertiary-fixed': '#e1e3e5',
        'on-primary-fixed': '#001945',
        'on-primary-fixed-variant': '#1e448b',
        background: '#faf8ff',
        'surface-variant': '#e2e2e8',
        'success-fixed': '#d9e2ff',
        'surface-container-high': '#e8e7ee',
        'secondary-fixed': '#d5e3fc',
        'on-secondary': '#ffffff',
        'surface-bright': '#faf8ff',
        'on-secondary-fixed-variant': '#3a485c',
        'primary-container': '#003178',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'on-surface': '#1a1b20',
        secondary: '#515f74',
        'secondary-fixed-dim': '#b9c7e0',
        'primary-fixed': '#d9e2ff',
        'on-tertiary-fixed': '#191c1e',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#9b9da0',
        'primary-fixed-dim': '#b0c6ff',
        'on-success-fixed': '#001945',
        'on-surface-variant': '#434651',
        'on-primary-container': '#7c9ce9',
        'outline-variant': '#c4c6d2',
        surface: '#faf8ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'header-height': '64px',
        lg: '24px',
        sm: '8px',
        gutter: '24px',
        md: '16px',
        xs: '4px',
        xl: '32px',
      },
      fontFamily: {
        'label-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'body-sm': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}